spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ruhadb
    username: root
    password: roEhddl1!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
#    type-aliases-package: com.example.domain

logging.level:
  org.hibernate.SQL: debug